### ISSUE TITLE
Unable to import library

### ISSUE THREAD

**Issue by edlaf** [databento/databento-python#72]
### Expected Behavior
import databento

### Actual Behavior
I'm unable to run any cell with import databento, either my kernel crashes or it just run indefinitely 

### Steps to Reproduce the Problem

1. create a cell in a notebook or a script with import databento in it

### Specifications

- OS Platform: I'm mac pro M1 on vs code
- Databento Version: Latest version of databento

**Comment by nmacholl** [comment]
Hey there. What is the error or exception you are seeing?

One thing to try is importing the dependencies of `databento-python` to see if any of these other packages are causing the problem. The dependencies are listed in the [pyproject.toml](https://github.com/databento/databento-python/blob/07d2f9a7ded0d4c6df9aca7bde0a42a1d38d3d5d/pyproject.toml).

**Comment by nmacholl** [comment]
I'm going to close this issue for now, but feel free to re-open it if there is more to discuss.
