### ISSUE TITLE
stype_in always 255

### ISSUE THREAD

**Issue by Kafuuaki** [databento/databento-python#73]
### Expected Behavior
When request data, stype_in shows a enum(parent etc)

### Actual Behavior
stype_in always show 255

### Steps to Reproduce the Problem

import databento as db

client = db.Live(key="XXX")

client.subscribe(
    dataset="GLBX.MDP3",
    schema="trades",
    stype_in="parent",
    symbols="ES.FUT",
)

client.add_callback(print)

client.start()

client.block_for_close(timeout=10)

### Specifications

- OS Platform:
- Databento Version:
0.42.0

**Comment by nmacholl** [comment]
Hey there. Can you tell me some more about how you are accessing `stype_in`?

For Live data, the DBN metadata's `stype_in` field will be 255, which translates to `None`. This is expected since a DBN file created from live data may contain multiple subscriptions with different input symbology types.

**Comment by nmacholl** [comment]
I'm going to close this issue for now, but feel free to re-open it if there is more to discuss.
