### ISSUE TITLE
Is there a self-hosted tsdb (`dbz`?) and any existing `docker` container?

### ISSUE THREAD

**Issue by goodboy** [databento/databento-python#9]
Hey y'all,

very very interested in trying out your tsdb but am wondering if there's any containerization work that's been done and is at least partially maintained?

If not happy to whip something up and publish it for others to try.

Salud!

**Comment by cjdsellers** [comment]
Hi @goodboy 

Thanks for your interest!

To clarify, this library doesn't actually include a time series database. It provides a thin client to our HTTP API for historical data streaming and batch download requests.

Could you tell us more about your specific use case?

**Comment by goodboy** [comment]
@cjdsellers ah yes my apologies, i hadn't read through your service docs enough 😹 

I was under the impression the project was more along the lines of something like [`marketstore`]() where you were providing the tsdb and client; i see now that the backend is all in your prop service yes?

the project i am working around is in search of something more reliable (cough with maybe less `go` and more `rust`) for our tsdb. i had seen this project after snooping your nautilus project and thought based on the client docs it looked like a great fit 😉 

> To clarify, this library doesn't actually include a time series database.
> It provides a thin client to our HTTP API for historical data streaming and batch download requests.

I presume `dbz` is used in your service and/or can be used without it as a form of tsdb though right? I haven't looked into that code base yet, but I guess we're after something that is foss, can be self-hosted, and more or less has parity perf and functionality with `marketstore`.

Sorry this derailed so much from the original question, i'll adjust the OP title.

**Comment by goodboy** [comment]
Ah, diggin a little i'm going to guess the http service is wrapping the [dbz-python](https://github.com/databento/dbz/blob/main/src/dbz-python/README.md) stuff yah?

**Comment by rkrn** [comment]
Yes.

Keep in mind `dbz` is not a database management system (like [Clickhouse](https://clickhouse.com/)) nor an embedded database (like [RocksDB](http://rocksdb.org/)). It's a presentation layer protocol (like [SBE](https://github.com/real-logic/simple-binary-encoding)) that can be used both as a file storage format or for messaging.

You could use it as a flat file, backing storage for a server — which is basically what we've done for our API backend — and get good performance out of it.

If you have an interest in `dbz`, keep in mind we'll be releasing major changes soon.

**Comment by goodboy** [comment]
@rkrn sweet sounds good.

Yeah, longer run if it becomes stable enough to be used in a similar way (with wrapping) as your http layer, we'll probably take it seriously.

I'm sure y'all know about the competition but just for the record [these are the tsdbs we've got eyes on atm](https://github.com/pikers/piker/issues/90).

I look forward to seeing the major updates have in store 🏄🏼
